### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by guyguy404** [jyFengGoGo/InstructDet#5]
When I run the code, I meet an error: 
```
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
I have no idea how to solve this problem.

The following is a record of my installation.

# Install Dependencies

```bash
$ nvcc -V
---
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
```

```bash
$ conda create -n InstructDet python=3.8 -y
$ conda activate InstructDet
```

```bash
$ pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116
---
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 numpy-1.24.4 pillow-10.3.0 requests-2.31.0 torch-1.13.1+cu116 torchaudio-0.13.1+cu116 torchvision-0.14.1+cu116 typing-extensions-4.11.0 urllib3-2.2.1
```

```bash
$ cd modules/fastchat
$ pip install -e .
---
Successfully built fschat
Installing collected packages: wcwidth, tokenizers, sentencepiece, pytz, pydub, nh3, ffmpy, appdirs, zipp, websockets, uc-micro-py, tzdata, tqdm, toolz, svgwrite, sniffio, smmap, six, shortuuid, setproctitle, sentry-sdk, semantic-version, safetensors, rpds-py, regex, pyyaml, python-multipart, pyparsing, pygments, pydantic-core, psutil, protobuf, prompt-toolkit, pkgutil-resolve-name, packaging, orjson, multidict, mdurl, markupsafe, markdown2, kiwisolver, h11, fsspec, frozenlist, fonttools, filelock, exceptiongroup, cycler, contourpy, click, attrs, async-timeout, annotated-types, aiofiles, yarl, wavedrom, uvicorn, tiktoken, referencing, python-dateutil, pydantic, markdown-it-py, linkify-it-py, jinja2, importlib-resources, huggingface-hub, httpcore, gitdb, docker-pycreds, anyio, aiosignal, transformers, starlette, rich, pandas, mdit-py-plugins, matplotlib, jsonschema-specifications, httpx, GitPython, aiohttp, accelerate, wandb, jsonschema, fastapi, altair, gradio, fschat
Successfully installed GitPython-3.1.43 accelerate-0.29.3 aiofiles-23.2.1 aiohttp-3.9.5 aiosignal-1.3.1 altair-5.3.0 annotated-types-0.6.0 anyio-4.3.0 appdirs-1.4.4 async-timeout-4.0.3 attrs-23.2.0 click-8.1.7 contourpy-1.1.1 cycler-0.12.1 docker-pycreds-0.4.0 exceptiongroup-1.2.1 fastapi-0.110.2 ffmpy-0.3.2 filelock-3.13.4 fonttools-4.51.0 frozenlist-1.4.1 fschat-0.2.15 fsspec-2024.3.1 gitdb-4.0.11 gradio-3.23.0 h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 huggingface-hub-0.22.2 importlib-resources-6.4.0 jinja2-3.1.3 jsonschema-4.21.1 jsonschema-specifications-2023.12.1 kiwisolver-1.4.5 linkify-it-py-2.0.3 markdown-it-py-2.2.0 markdown2-2.4.13 markupsafe-2.1.5 matplotlib-3.7.5 mdit-py-plugins-0.3.3 mdurl-0.1.2 multidict-6.0.5 nh3-0.2.17 orjson-3.10.1 packaging-24.0 pandas-2.0.3 pkgutil-resolve-name-1.3.10 prompt-toolkit-3.0.43 protobuf-4.25.3 psutil-5.9.8 pydantic-2.7.1 pydantic-core-2.18.2 pydub-0.25.1 pygments-2.17.2 pyparsing-3.1.2 python-dateutil-2.9.0.post0 python-multipart-0.0.9 pytz-2024.1 pyyaml-6.0.1 referencing-0.35.0 regex-2024.4.16 rich-13.7.1 rpds-py-0.18.0 safetensors-0.4.3 semantic-version-2.10.0 sentencepiece-0.2.0 sentry-sdk-2.0.0 setproctitle-1.3.3 shortuuid-1.0.13 six-1.16.0 smmap-5.0.1 sniffio-1.3.1 starlette-0.37.2 svgwrite-1.4.3 tiktoken-0.6.0 tokenizers-0.13.3 toolz-0.12.1 tqdm-4.66.2 transformers-4.28.1 tzdata-2024.1 uc-micro-py-1.0.3 uvicorn-0.29.0 wandb-0.16.6 wavedrom-2.0.3.post3 wcwidth-0.2.13 websockets-12.0 yarl-1.9.4 zipp-3.18.1
```

```bash
$ cd ../llava
$ pip install -e .
---
Building wheels for collected packages: llava
  Building editable for llava (pyproject.toml) ... done
  Created wheel for llava: filename=llava-0.1.0-0.editable-py3-none-any.whl size=7095 sha256=23fee1245479abea032ab60ea0b277db94ebb8514a068bd202b01ec84ff117fd
  Stored in directory: /tmp/pip-ephem-wheel-cache-ho0rg_ni/wheels/e9/6a/ed/420149178cd3ac29443ba350885d9cde0bde3bf97c48ea1020
Successfully built llava
Installing collected packages: einops, transformers, llava
  Attempting uninstall: transformers
    Found existing installation: transformers 4.28.1
    Uninstalling transformers-4.28.1:
      Successfully uninstalled transformers-4.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fschat 0.2.15 requires transformers<4.29.0,>=4.28.0, but you have transformers 4.31.0 which is incompatible.
```

```bash
$ cd ../instruct_filter/CLIP
$ pip install -e .
---
Installing collected packages: ftfy, clip
  Running setup.py develop for clip
Successfully installed clip-1.0 ftfy-6.2.0
```

```bash
$ pip install -r requirements.txt
---
Installing collected packages: braceexpand, antlr4-python3-runtime, webdataset, portalocker, omegaconf, decord, iopath
Successfully installed antlr4-python3-runtime-4.9.3 braceexpand-0.1.7 decord-0.6.0 iopath-0.1.10 omegaconf-2.3.0 portalocker-2.8.2 webdataset-0.2.86
```

# Run

After downloading the model weights and datasets, and modifying paths in config file, I tried to run the code.

## Try 1

```bash
$ bash scripts/run.sh 0 100
---
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from easydict import EasyDict
ModuleNotFoundError: No module named 'easydict'
```

### Solution

```bash
$ pip install easydict
---
Installing collected packages: easydict
Successfully installed easydict-1.13
```

## Try 2

```bash
$ bash scripts/run.sh 0 100
---
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/.../InstructDet/logs/2024-04-26-11-12-37.log'
```

### Solution

Create a log folder under InstructDet.

## Try 3

```bash
$ bash scripts/run.sh 0 100
---
Loading LLaVA ...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:16<00:00,  5.46s/it]
0it [00:14, ?it/s]
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    main(cfg)
  File "main.py", line 65, in main
    jsonlines = describe_image(cfg.llava_config)
  File "/.../InstructDet/modules/llava/llava/eval/run_llava_dsp.py", line 141, in describe_image
    output_ids = model.generate(
  File "/.../miniconda3/envs/InstructDet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/.../miniconda3/envs/InstructDet/lib/python3.8/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/.../miniconda3/envs/InstructDet/lib/python3.8/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by guyguy404** [comment]
According to [https://github.com/haotian-liu/LLaVA/issues/896](https://github.com/haotian-liu/LLaVA/issues/896)

> fix the probelm with 1.1.1tag code.

Go to the github page of llava and download code with tag `1.1.1`. Use it to replace `./modules/llava`, while keeping `./modules/llava/llava/data` and `./modules/llava/llava/eval/run_llava_dsp.py`.

This helped me to solve the above problem. Under vscode debug mode, the code can run without error.
