### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM: size mismatch for lm_head.weight:

### ISSUE THREAD

**Issue by guyguy404** [jyFengGoGo/InstructDet#6]
When loading minigpt4 in local pipeline, I encountered the following error:
```bash
Traceback (most recent call last):
  File "/home/.../InstructDet/main.py", line 175, in <module>
    main(cfg)
  File "/home/.../InstructDet/main.py", line 89, in main
    generator = MiniGPT4Generator(vlm_config.minigpt4)
  File "/home/.../InstructDet/modules/minigpt4/generate.py", line 54, in __init__
    self.build_chat()
  File "/home/.../InstructDet/modules/minigpt4/generate.py", line 97, in build_chat
    self.model = model_cls.from_config(model_config).to('cuda')
  File "/home/.../InstructDet/modules/minigpt4/minigpt4/models/mini_gpt4.py", line 251, in from_config
    model = cls(
  File "/home/.../InstructDet/modules/minigpt4/minigpt4/models/mini_gpt4.py", line 101, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "/home/.../miniconda3/envs/InstructDet/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2903, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/.../miniconda3/envs/InstructDet/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3310, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        size mismatch for lm_head.weight: copying a param with shape torch.Size([32000, 5120]) from checkpoint, the shape in current model is torch.Size([32001, 5120]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

If I add `ignore_mismatched_sizes=True`, the generated sentences are totally messy codes.
How can I fix this problem?

**Comment by guyguy404** [comment]
I simply replace [vicuna-13b-v0-merged](https://huggingface.co/j-min/vicuna-13b-v0-merged) in local pipeline with [vicuna-13b-v1.3](https://huggingface.co/lmsys/vicuna-13b-v1.3) in global pipeline.
Then the code can run without error.
